#!/bin/sh
# script to start all semaphores for the dining philosophers:

echo ':l philo_ext
      start_room' | pakcs &
echo ':l philo_ext
      start_fork0' | pakcs &
echo ':l philo_ext
      start_fork1' | pakcs &
echo ':l philo_ext
      start_fork2' | pakcs &
echo ':l philo_ext
      start_fork3' | pakcs &
echo ':l philo_ext
      start_fork4' | pakcs &

# now you can start the philosophers
