#!/bin/sh
#
# Configure PAKCSHOME/bin/.pakcs_variables with correct environment variables
#

# Compute home of PAKCS installation:
PAKCSHOME=`(cd "\`dirname \"$0\"\`" > /dev/null ; pwd)`/..

# Distribution version of the pakcsinitrc file:
PAKCSINITRC=$PAKCSHOME/bin/.pakcs_variables

# Initial repository version of the pakcsinitrc file:
REPOSINITRC=$PAKCSHOME/scripts/pakcs_variables.sh

# check for HOME variable
if [ "$HOME" = "" ] ; then
  echo "Cannot configure PAKCS since environment variable HOME not set!"
  exit 1
fi

# Local version of the pakcsinitrc file:
HOMEINITRC=$HOME/.pakcsinitrc

if [ -f "$PAKCSINITRC" ] ; then
  # Save old installed version of pakcsinitrc:
  cp -p "$PAKCSINITRC" "$PAKCSINITRC.bak"
elif [ -f "$REPOSINITRC" ] ; then
  # The following is only relevant for repository checkouts:
  cp "$REPOSINITRC" "$PAKCSINITRC"
  cp "$REPOSINITRC" "$PAKCSINITRC.bak"
elif [ ! -f "$PAKCSINITRC" ] ; then
  echo "ERROR: Incomplete distribution: $PAKCSINITRC is missing!"
  exit 1
fi

# override definition of SICSTUS etc with values of last install, if possible:
if [ -f "$HOMEINITRC" ] ; then
  cp -p "$HOMEINITRC" "$HOMEINITRC.bak"
  # Update $PAKCSINITRC with values of last installation:
  for i in `sed -n '/^[A-Za-z]*=/p' < "$HOMEINITRC.bak"`
  do 
    VAR=`expr $i : '\(.*\)=.*'`
    VALUE=`expr $i : '.*=\(.*\)'`
    OLDENTRY=`sed -n '/^'$VAR'=/p' < "$PAKCSINITRC.bak"`
    OLDVALUE=`expr "$OLDENTRY" : '.*=\(.*\)'`
    #echo VAR=$VAR \| VALUE=$VALUE \| OLDVALUE=$OLDVALUE
    if [ "$VALUE" = "$OLDVALUE" ] ; then
      mv "$PAKCSINITRC" "$PAKCSINITRC.sav"
      cat "$PAKCSINITRC.sav" | sed 's|^'$VAR'=.*$|'$VAR=$VALUE'|' > "$PAKCSINITRC"
    else
      if [ -n "$OLDVALUE" ] ; then
        SUGGEST=$OLDVALUE
      else
        SUGGEST=$VALUE
      fi
      echo -n "Initial value for $VAR: [$SUGGEST] "
      read NEWVALUE
      if [ "$NEWVALUE" = "" ] ; then
        NEWVALUE=$SUGGEST
      fi
      mv "$PAKCSINITRC" "$PAKCSINITRC.sav"
      cat "$PAKCSINITRC.sav" | sed 's|^'$VAR'=.*$|'$VAR=$NEWVALUE'|' > "$PAKCSINITRC"
    fi
  done
  rm -f "$PAKCSINITRC.sav"
else
  cp "$PAKCSINITRC" "$HOMEINITRC"
fi

# Load the definition of SICSTUSDIR and SWIPROLOG:
. "$HOMEINITRC" # to get possibly old definition of SICSTUSDIR etc
. "$PAKCSINITRC"

# try to define SICSTUSDIR if it is not defined:
rm -f bin/sicstusprolog # delete possible old definition
if [ -z "$SICSTUSDIR" ] ; then
  if [ -n "$SICSTUS" -a -x "$SICSTUS" ] ; then
    SICSTUSBIN=$SICSTUS
  else
    SICSTUSBIN=`which sicstus 2> /dev/null`
  fi
  if [ -n "$SICSTUSBIN" ] ; then
    SICSTUSDIR=`expr $SICSTUSBIN : '\(.*\)/bin/sicstus'`
  else
    SICSTUSDIR=
  fi
  if [ -x "$SICSTUSDIR/bin/sicstus" ] ; then
    echo "halt." | $SICSTUS > /tmp/sicstusout$$ 2>&1
    if [ $? -eq 0 ]; then
      rm /tmp/sicstusout$$
      echo "SICSTUSDIR not defined $HOMEINITRC, but I have found:"
      echo $SICSTUSDIR
      echo -n "Should I use this for PAKCS? (y/n) "
      read ANSWER
      if [ xx$ANSWER = xxy ] ; then
        cd bin
        mv "$PAKCSINITRC" "$PAKCSINITRC.sav"
	cat "$PAKCSINITRC.sav" | sed 's|^SICSTUSDIR=.*$|SICSTUSDIR='$SICSTUSDIR'|' > "$PAKCSINITRC"
        rm -f "$PAKCSINITRC.sav"
        echo "Definition of SICSTUSDIR changed in $PAKCSINITRC"
        cd "$PAKCSHOME"
        export SICSTUSDIR
      else
        SICSTUSDIR=
        if [ -z "$SWIPROLOG" ] ; then
          echo "Please put a correct definition for SICSTUS in $HOMEINITRC"
          echo "if you want to use the PAKCS/Curry2Prolog compiler."
        fi
      fi
    else
      rm /tmp/sicstusout$$
      SICSTUSDIR=
    fi
  else
    SICSTUSDIR=
  fi
fi

# Create symbolic link bin/sicstusprolog if SICSTUSDIR is defined:
cd bin
if [ -n "$SICSTUSDIR" ] ; then
  # test SICStus Prolog:
  SICSTUS=$SICSTUSDIR/bin/sicstus
  echo "halt." | $SICSTUS > /tmp/sicstusout$$ 2>&1
  if [ $? -ne 0 ]; then
    echo "ERROR: Cannot execute SICStus-Prolog ($SICSTUS):"
    cat /tmp/sicstusout$$
    echo "Please put a correct definition for SICSTUSDIR in $HOMEINITRC !"
    rm /tmp/sicstusout$$
    exit 1
  else
    #ln -s .pakcs_wrapper sicstusprolog
    ln -s "$SICSTUSDIR/bin/sicstus" sicstusprolog
    rm /tmp/sicstusout$$
  fi
fi
cd "$PAKCSHOME"

# try to define SWIPROLOG if SICSTUS and SWIPROLOG are not defined:
rm -f bin/swiprolog # delete possible old definition
if [ -z "$SICSTUSDIR" -a -z "$SWIPROLOG" ] ; then
  echo "No SICStus-Prolog defined or found, looking for SWI-Prolog..."
  SWIPROLOG=`which swipl 2> /dev/null`
  if [ ! -x "$SWIPROLOG" ] ; then
    SWIPROLOG=`which pl 2> /dev/null`
  fi
  if [ -x "$SWIPROLOG" ] ; then
    echo "halt." | $SWIPROLOG > /tmp/swiprologout$$ 2>&1
    if [ $? -eq 0 -a `grep -c SWI-Prolog /tmp/swiprologout$$` -gt 0 ]; then
      rm /tmp/swiprologout$$
      echo "SWIPROLOG not defined $HOMEINITRC, but I have found:"
      echo $SWIPROLOG
      echo -n "Should I use this for PAKCS? (y/n) "
      read ANSWER
      if [ xx$ANSWER = xxy ] ; then
        cd bin
        mv "$PAKCSINITRC" "$PAKCSINITRC.sav"
	cat "$PAKCSINITRC.sav" | sed 's|^SWIPROLOG=.*$|SWIPROLOG='$SWIPROLOG'|' > "$PAKCSINITRC"
        rm -f "$PAKCSINITRC.sav"
        echo "Definition of SWIPROLOG changed in $PAKCSINITRC"
        cd "$PAKCSHOME"
        export SWIPROLOG
        cd bin ; ln -s "$SWIPROLOG" swiprolog
      else
        SWIPROLOG=
        echo "Please put a correct definition for SICSTUSDIR or SWIPROLOG in $HOMEINITRC"
        echo "if you want to use the PAKCS/Curry2Prolog compiler."
      fi
    else
      rm /tmp/swiprologout$$
      SWIPROLOG=
    fi
  else
    SWIPROLOG=
  fi
fi
cd "$PAKCSHOME"

# Create symbolic link bin/swiprolog if SWIPROLOG is correctly defined:
cd bin
if [ -n "$SWIPROLOG" ] ; then
  # test SWIPROLOG:
  echo "halt." | $SWIPROLOG > /tmp/swiprologout$$ 2>&1
  if [ $? -ne 0 ]; then
    echo "ERROR: Cannot execute SWI-Prolog ($SWIPROLOG):"
    cat /tmp/swiprologout$$
    echo "Please put a correct definition for SWIPROLOG in $HOMEINITRC !"
    rm /tmp/swiprologout$$
    exit 1
  else
    ln -s "$SWIPROLOG" swiprolog
    rm /tmp/swiprologout$$
  fi
fi
cd "$PAKCSHOME"

# check whether $PAKCSINITRC was changed and, if not, keep old version:
cmp -s "$PAKCSINITRC" "$PAKCSINITRC.bak"
if [ $? -eq 0 ]; then
  mv -f "$PAKCSINITRC.bak" "$PAKCSINITRC"
fi

# Save current values for future installations:
cp "$PAKCSINITRC" "$HOMEINITRC"
chmod 644 "$PAKCSINITRC"

# Report current values:
echo '======================================================================'
echo 'PAKCS installation configured with (saved in '$HOME'/.pakcsinitrc):'
echo "SICSTUSDIR=$SICSTUSDIR"
echo "SWIPROLOG=$SWIPROLOG"
echo '======================================================================'
